import Head from 'next/head';
import Image from 'next/image';
import SideNav from './sideinfo';
import HeaderNav from './headernav';
import {usePathname} from 'next/navigation';

export default function Header() {
    const path = usePathname();
    return(
        <>
            <Head>
                <title>쌍용대학교</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/images/logo.png" />
            </Head>
            <header>
                    <div>
                        <button type="button">로그인</button>
                        {path === "/" ? <SideNav /> : ''}
                    </div>
                    <span><Image width={300} height={150} src="/images/logo.png" alt="쌍용대학교"/></span>
            </header>
            {path === "/" ? '' : <HeaderNav />}
            <style jsx>{`
                header {
                    height:220px;
                    border-bottom: solid 1px black;
                    align-items: center;
                }
                header div {
                    padding: 30px 50px 0 0;
                    height: 35px;
                }
                div button{
                    float: right;
                    border : 0;
                    border-radius: 10px;
                    padding: 5px 10px 5px 10px; 
                    box-shadow: 4px 4px 4px;
                }
                span{
                    cursor: pointer;
                    display: flex;
                    justify-content: center;
                }
            `}</style>
        </>
    );

}