import Head from 'next/head';
import Image from 'next/image';

export default function Header() {
    return(
        <>
            <Head>
                <title>쌍용대학교</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/images/logo.png" />
            </Head>
            <header>
                    <div>
                        <button type="button">로그인</button>
                    </div>
                    <span><Image width={300} height={150} src="/images/logo.png" alt="쌍용대학교"/></span>
                <style jsx>{`
                    header {
                        height:220px;
                        border-bottom: solid 1.5px black;
                        align-items: center;
                    }
                    div{
                        text-align: right;
                        padding: 30px 50px 0 0;
                    }
                    button{
                        float: right;
                        all:unset;
                    }
                    span{
                        cursor: pointer;
                        display: flex;
                        justify-content: center;
                    }
                `}</style>
            </header>
        </>
    );

}